---
provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: rhel-7
    driver:
      image_id: ami-8b8c57f8
      name: ec2
      aws_ssh_key_id: emea-sa-shared
      region: eu-west-1
      availability_zone: b
      require_chef_omnibus: true
      instance_type: t2.micro
      security_group_ids: ["sg-8436d7e3"]
      tags: {
        Name: "cad-kitchen",
        created-by: "test-kitchen"
      }
    transport:
      username: ec2-user
      ssh_key: ~/.ssh/emea-sa-shared.pem
         
suites:
  - name: default
    run_list:
      - recipe[sitedbaas::default]
      - recipe[sitedbaas::audit-apache]
    attributes: