---
driver:
  name: docker
  use_sudo: false

driver_config:
  network:
    - ['forwarded_port', {guest: 80, host: 80}]
    - ['private_network', {ip: '33.33.33.10'}]

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[sitedbaas::default]
      - recipe[sitedbaas::ubuntu-audit-apache]
    attributes:
