---
provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: ec2-ubuntu-14.04
    driver:
      image_id: ami-be5cf7cd
      name: ec2
      aws_ssh_key_id: emea-sa-shared
      region: eu-west-1
      availability_zone: b
      require_chef_omnibus: true
      instance_type: m1.small
      security_group_ids: ["sg-8436d7e3"]
      tags: {
        Name: "cad-kitchen",
        created-by: "test-kitchen"
      }
    transport:
      username: ubuntu
      ssh_key: ~/.ssh/emea-sa-shared.pem
         
suites:
  - name: default
    run_list:
      - recipe[sitedbaas::default]
      - recipe[sitedbaas::ubuntu-audit-apache]
    attributes: