name 'sitedbaas'
maintainer 'chef'
maintainer_email 'solutions-architects@chef.io'
license 'all_rights'
description 'Installs/Configures sitedbaas'
long_description 'Installs/Configures sitedbaas'
version '2.0.1'
depends 'httpdbaas'
